# Generated by Django 5.2.3 on 2025-07-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
